<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('surat_terbit', function (Blueprint $table) {
            // Track when PDF file is actually generated by the worker
            $table->timestamp('pdf_generated_at')->nullable()->after('pdf_status');
        });
    }

    public function down(): void
    {
        Schema::table('surat_terbit', function (Blueprint $table) {
            $table->dropColumn('pdf_generated_at');
        });
    }
};
